#!/usr/bin/env node
// Concatenate src/client/*.js into the DSH ModuleLoader bundle at client.js.
// Browser half cannot use ESM imports; this is the only supported split.

import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const srcDir = join(root, 'src', 'client')
const outFile = join(root, 'client.js')

export const CLIENT_LAYERS = [
  'constants.js',
  'css/tokens.js',
  'css/sidebar-island.js',
  'css/conversation-pane.js',
  'css/conversation-title.js',
  'css/conversation-scroll.js',
  'css/composer.js',
  'css/overlays.js',
  'css/sidebar-chrome.js',
  'css/cards.js',
  'css/settings.js',
  'css/a11y.js',
  'css.js',
  'storage.js',
  'i18n.js',
  'wallpaper-state.js',
  'optics-sdf.js',
  'optics-map.js',
  'optics-measure.js',
  'generated-optics-fallbacks.js',
  'controller-styles.js',
  'controller.js',
  'settings-import.js',
  'settings-view.js',
  'settings.js',
  'runtime-scheduler.js',
  'metal.js',
  'metrics.js',
  'apply.js',
]

const HEADER = `// Generated by scripts/build-client.mjs from src/client/. Edit those files.
//
// dsh-liquid-glass —— wallpaper + optional Liquid Glass overlay (Client)
//
// Overlay only. Official scroll/layout ownership stays with DSH. Surfaces may
// take margin/padding/radius; ConversationRoot is never a slab. No DOM moves,
// no MutationObserver, no stamping.
window.__ModuleLoader__.load({
  id: 'dsh-liquid-glass',
  factory: (require) => {
    var module = { exports: {} }
    var exports = module.exports
    var React = require('react')
`

const FOOTER = `
    exports.name = name
    exports.inject = inject
    exports.apply = apply
    return module.exports
  },
})
`

export async function renderClient() {
  const parts = []
  for (const name of CLIENT_LAYERS) {
    const body = await readFile(join(srcDir, name), 'utf8')
    parts.push(body.replace(/\n+$/, ''))
  }
  return HEADER + '\n' + parts.join('\n\n') + '\n' + FOOTER
}

export async function writeClient() {
  const next = await renderClient()
  await writeFile(outFile, next)
  return outFile
}

export async function clientIsFresh() {
  const expected = await renderClient()
  const actual = await readFile(outFile, 'utf8')
  return expected === actual
}

const invoked = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]
if (invoked) {
  if (process.argv.includes('--check')) {
    if (!(await clientIsFresh())) {
      console.error('client.js is stale. Run npm run build')
      process.exit(1)
    }
  } else {
    await writeClient()
  }
}
